= Mailing list operator
:toc:
:toclevels: 4
:toc-placement!:

Issue: https://github.com/bisq-network/roles/issues/26[bisq-network/roles#26]

toc::[]

== Purpose

To maintain a mailing list suitable for discussions about Bisq development and other forms of contribution.

== Motivation

The old https://groups.google.com/forum/#!forum/bitsquare[Bitsquare Google Group] has fallen out of use. This is partially due to the fact that we set up a Mailchimp-based newsletter later on in the project, and the purpose of the Google Group became unclear afterwards. Our motivation here is to replace the Google Group with a our own GNU Mailman instance at https://lists.bisq.network, and to use it to manage a clearly-defined _contributors_ mailing list. Mailman is well-understood and well-liked by free software contributors, and so we assume it will be a good fit for Bisq contributors going forward. The Mailchimp-based newsletter will stick around, as it is an idiomatic way to stay in touch with Bisq's not necessarily technical users.

== Privileges

The operator will have administrative access to the Mailman server at https://lists.bisq.network, as well as administrative access to the infrastructure that hosts it.

== General Requirements

The operator MUST:

 - post a bond of **TBD** BSQ to assume this role
 - maintain this role specification document

== Special Requirements

The operator MUST:

 - keep the Mailman installation up and running
 - keep the Mailman installation up to date with latest patches
 - respond promptly to any questions / requests in the #lists Slack channel (recommendation: set your Slack notification preferences for that channel to be notified on "all new messages" so you don’t miss anything)
 - acknowledge / respond promptly to any issues submitted to the https://github.com/bisq-network/lists[bisq-network/lists] GitHub repository
