= Bisq Network Roles

This repository gives you a transparent overview about all current roles within the Bisq Network. It provides the viewer with details about the purpose, motivation, privileges, requirements and responsibilities of all roles. This will ensure clarity about ones own role, help identifying other roles and facitilitate the compensation process.

The **owner of the role** is responsible for **creating and maintaining** of his/her **role description**. 

== How to Create a New Role?

1. Create **New File**
1. **Name** Your File according to the defined syntax (eg. "role-maintainer.adoc")
1. **Edit** Your Role according to the https://github.com/bisq-network/roles/blob/master/TEMPLATE.adoc[Template]
1. **Propose** New File
1. You're done? Then you are ready to Create a **Pull Request**
1. Wait for Confirmation


== List of Roles in the Network:

https://github.com/bisq-network/roles/blob/master/ambassador.adoc[Ambassador]
https://github.com/bisq-network/roles/blob/master/bitcointalk-bisq-thread-operator.adoc[Bitcointalk Bisq Thread Operator]
https://github.com/bisq-network/roles/blob/master/bitcoinj-maintainer.adoc[Botcoinj Maintainer]
https://github.com/bisq-network/roles/blob/master/bsq-explorer-operator-and-maintainer.adoc[BSQ Explorer Operator and Maintainer]
https://github.com/bisq-network/roles/blob/master/bsq-record-keeper.adoc[BSQ Record Keeper]
https://github.com/bisq-network/roles/blob/master/comp-maintainer.adoc[Comp Maintainer]
https://github.com/bisq-network/roles/blob/master/dao-maintainer.adoc[DAO Maintainer]
https://github.com/bisq-network/roles/blob/master/disclosure-forum-operator.adoc[Discourse Forum Operator]
https://github.com/bisq-network/roles/blob/master/dns-operator.adoc[DNS Operator]
https://github.com/bisq-network/roles/blob/master/docs-maintainer.adoc[Docs Maintainer]
https://github.com/bisq-network/roles/blob/master/economic-advisor.adoc[Economic Advisor]
https://github.com/bisq-network/roles/blob/master/exchange-arbitrator.adoc[Exchange Arbitrator]
https://github.com/bisq-network/roles/blob/master/exchange-maintainer.adoc[Exchange Maintainer]
https://github.com/bisq-network/roles/blob/master/exchange-payment-method-expert.adoc[Exchange Payment Method Expert]
https://github.com/bisq-network/roles/blob/master/exchange-statistics-websiteapi-operator-and-maintainer.adoc[Exchange Statistics Website/API Operator and Maintainer]
https://github.com/bisq-network/roles/blob/master/founder.adoc[Founder]
https://github.com/bisq-network/roles/blob/master/freenode-irc-operator.adoc[Freenode IRC Operator]
https://github.com/bisq-network/roles/blob/master/github-organization-operator.adoc[GitHub Organization Operator]
https://github.com/bisq-network/roles/blob/master/mailchimp-newsletter-administrator.adoc[Mailchimp Newsletter Administrator]
https://github.com/bisq-network/roles/blob/master/network-monitor-operator-and-maintainer.adoc[Network Monitor Operator and Maintainer]
https://github.com/bisq-network/roles/blob/master/pricenode-maintainer.adoc[Pricenode Maintainer]
https://github.com/bisq-network/roles/blob/master/pricenode-operator.adoc[Pricenode Operator]
https://github.com/bisq-network/roles/blob/master/proposals-maintainer.adoc[Proposals Maintainer]
https://github.com/bisq-network/roles/blob/master/reddit-operator.adoc[Reddit Operator]
https://github.com/bisq-network/roles/blob/master/roles-maintainer.adoc[Roles Maintainer]
https://github.com/bisq-network/roles/blob/master/seednode-maintainer.adoc[Seednode Maintainer]
https://github.com/bisq-network/roles/blob/master/seednode-operator.adoc[Seednode Operator]
https://github.com/bisq-network/roles/blob/master/slack-workspace-owner.adoc[Slack Workspace Owner]
https://github.com/bisq-network/roles/blob/master/statsnode-maintainer.adoc[Statsnode Maintainer]
https://github.com/bisq-network/roles/blob/master/telegram-operator.adoc[Telegram Operator]
https://github.com/bisq-network/roles/blob/master/transifex-operator.adoc[Transifex Operator]
https://github.com/bisq-network/roles/blob/master/travis-ci-operator.adoc[Travis CI Operator]
https://github.com/bisq-network/roles/blob/master/vimeo-operator.adoc[Vimeo Operator]
https://github.com/bisq-network/roles/blob/master/website-operator-and-maintainer.adoc[Website Operator and Maintainer]
https://github.com/bisq-network/roles/blob/master/writer-editor.adoc[Writer/Editor]
