= Twitter operator
:toc:
:toclevels: 4
:toc-placement!:

Issue: https://github.com/bisq-network/roles/issues/21[bisq-network/roles#21]

toc::[]

== Purpose

To provide a single, authoritative and trustworthy https://twitter.com/bisq_network[@bisq_network] Twitter account that anyone can:

 - follow, to stay up to date with Bisq;
 - @mention, to reference Bisq in conversation with others;
 - @mention, to ask questions about Bisq and provide feedback


== Motivation

Twitter is an important communication channel and news source for many people in Bisq's larger community. Most Bisq contributors operate personal Twitter accounts, but no one Bisq contributor should, by default, maintain control over the official @bisq_network account. This document specifies the requirements for assuming the role of @bisq_network Twitter account operator, such that (a) potentially any contributor can fulfill the requirements with minimal time and effort, and (b) account followers get consistent, valuable from it.

In general, the idea is that announcements, observations and opinions about the Bisq network should come from contributors' own personal Twitter accounts, and that the primary role of the @bisq_network account is to follow these contributors and 'curate' their content by liking and retweeting it. This principle is expanded upon in various sections below.


== Privileges

 - Control of the @bisq_network and (legacy) @bitsquare_ Twitter accounts.


== General Requirements

=== Bonding
The operator MUST post a bond of **TBD** BSQ to assume this role.

=== Reporting
The operator SHOULD post a monthly report in the form of a comment on the linked GitHub issue for this role. The report SHOULD include (but is not limited to):

 - A recap of the statistics available in Twitter Analytics;
 - Screenshot(s) from Twitter Analytics as appropriate;
 - Operator commentary

An example of this kind of report can be seen https://github.com/bisq-network/roles/issues/21#issuecomment-348463070[here].

=== Collaboration
All tweets to and from the account are posted in the `#twitter` channel of the Bisq Slack team. The operator MAY discuss tweets with other contributors in this channel, especially when in doubt whether or how to respond. If necessary, the operator MAY escalate specific tweets to specific contributors by reaching out to them directly. In any case, the operator SHOULD use their discretion in collaborating or escalating tweets in whatever way they see fit, so as to ensure an accurate and timely response to questions or comments about Bisq on Twitter.

=== Compensation
The operator MUST issue compensation requests to be awarded BSQ for their efforts. For convenience, such reports MAY be kept concise, simply linking to the current month's report (as per link:#reporting[Reporting] above).


== Special Requirements

=== Notifications
The operator SHOULD set themselves up to receive Twitter notifications in whatever way they see fit, such that they are able to fulfill the requirements that follow below.

=== Retweets
The account SHOULD retweet Bisq-related tweets from the people it follows, subject to the discretion of the account operator. Contributor tweets should not be "mechanistically" retweeted, but rather curated to avoid the account becoming repetitive or noisy, and to avoid retweeting negative or otherwise unproductive content.

The account MUST retweet release announcements made by Bisq network repository maintainers as soon as possible, and preferably immediately, but in any case within 24 hours.

=== Replies
The account SHOULD reply to tweets that ask @bisq_network a direct question. When feasible, the reply SHOULD contain the answer to the question being asked, but the reply MAY also simply redirect the questioner to a more appropriate venue, e.g. the Bisq forum or a particular Bisq repository's GitHub issues.

The account MAY reply to tweets mentioning @bisq_network, if the operator believes that the most effective action would be to tweet a reply directly from the @bisq_network account.

The account SHOULD reply to tweets mentioning @bisq_network in order to correct objective inaccuracies.

The account SHOULD NOT engage in extended Twitter conversations and MUST NOT engage in contentious debate or argument. If extended conversation or "defense" of Bisq is necessary, the account should let individual contributors engage from their own personal Twitter accounts.

=== Following
The account MUST follow current Bisq network contributors. A current contributor is anyone who has had a compensation request accepted in the preceding 3 months UNLESS the contributor (a) does not have a Twitter account, or (b) indicates they do not wish to be followed (see below).

The account MAY follow any number of alumni contributors. An alumni contributor is anyone who has had a compensation request accepted in the past, but who has not had a request accepted in the last 3 months. The specific set of alumni contributors that is followed is left to the operator's discretion.

The account MUST unfollow anyone who indicates they do not want to be followed.

The account MUST NOT follow anyone other than the accounts enumerated above.

=== Likes
The account MAY like any bisq-related tweet at the operator's discretion. The definition of "bisq-related" is also left to the operator's discretion, but the operator SHOULD take a conservative approach here. If in doubt, leave it out.

=== Moments
Pending further discussion, the account SHOULD NOT create or maintain any Moments. 

=== Lists
Pending further discussion, the account SHOULD NOT create or maintain any Lists. 

=== Profile

==== Username
The account username MUST remain "@bisq_network".

==== Name
The name MUST be "Bisq" and MUST NOT be amended to promote certain views, e.g. `[UASF]` or `[NO2X]` as is sometimes done in the larger Bitcoin community.

==== Profile photo
The profile photo MUST remain the official "Bisq cat" image.

==== Header image
The header image MAY be changed at the operator's discretion, but the operator SHOULD discuss any such changes with a quorum of other contributors first to ensure rough consensus if the image is changing significantly.

==== Website
The website field MUST be set to `https://bisq.network`.

=== Verification
The @bisq_network account is not and CAN NOT become a verified account. Per https://support.twitter.com/articles/20174631[Twitter's verification documentation], verifying organization or company accounts require "an organization or company email address". The Bisq network is not a company or traditional organization and as such has no "organization email addresses".

=== Ads
The acccount SHALL NOT purchase any Twitter ads or otherwise 'promote' tweets.

=== Analytics
See link:#reporting[Reporting] above.

=== Settings and Privacy

==== Account

===== Login verification
The account MUST have 2FA ("login verification") enabled at all times. The operator SHOULD configure the use of an authenticator app (e.g. Google Authenticator) instead of relying on SMS for 2FA, which is known to be insecure.

=== Other Twitter accounts
The operator will also be responsible for the legacy @bitsquare_ account, which is now inactive. The operator SHOULD subscribe to notifications from this account, but the operator SHOULD NOT tweet from this account.
